#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Aug  8 09:34:19 2019

@author: dan
"""



import re




dateDecidedRe0 = re.compile(r'decided\:\s*(\w+\s+\d+\,\s*\d\d\d\d)')
dateDecidedRe1 = re.compile(r'decided\:\s*(\w+\s+\d+\,\s*\d\d)')
dateFiledRe0 = re.compile(r'FILED\:*\s*(\w+\s+\d+\,\s*\d\d\d\d)')
dateDatedRe0 = re.compile(r'dated\:\s*(\w+\s+\d+\,\s*\d\d\d\d)')
dateDatedRe1 = re.compile(r'dated\:\s*(\w+\s+\d+\,\s*\d\d)')
dateDatedRe2 = re.compile(r'date\:\s*(\w+\s+\d+\,\s*\d\d\d\d)')
finalReportDateRe0 = re.compile(r'final\sreport\:\s*(\w+\s+\d+\,\s*\d\d\d\d)')
standardDateRe0 = re.compile(r'(\w\w\w+\s(\d|\d\d)\,\s*\d\d\d\d)')
standardDateRe1 = re.compile(r'(\w\w\w+\s(\d|\d\d)\,\s*\d\d)')

caseNoRE1 = re.compile(r"no\.?\s?\d{1,4}\,\s?\d\d\d\d", flags=re.IGNORECASE) # DE Supreme Court Style: No. 345, 2018
caseNoRE2 = re.compile(r"c\.a\.\s?no\.?\:?\s?\d{2,5}(\-|\s)?[a-z]{1,4}", flags=re.IGNORECASE) # DE Chancery Old Style: C.A. No. 5678-VCS
caseNoRE3 = re.compile(r"c\.a\.\s?no\.?\:?\s?([a-z0-9]{2,4}(\s|\-)){2,4}(\(?\w\w\w(\)|\s))?", flags=re.IGNORECASE) # DE Superior Court Style: C.A. No. 07C-01-202 MMJ
caseNoRE4 = re.compile(r"file\s?no\.?\s[0-9a-z]{2,5}(\s|\-)[0-9a-z]{2,5}(\s|$)(\([a-z]\))?", flags=re.IGNORECASE) # File Nos. from DE Family Court: File No. CN15-02666 (S)
caseNoRE5 = re.compile(r"((petition)|(pet\.?))\snos?\.?\s?\d\d(\-|\s)\d{3,6}(\s|$|\,)\s?(\d\d(\-|\s)\d{3,6})?", flags=re.IGNORECASE) # Petition numbers from DE family court: Petition No. 17-30245; Petition Nos. 17-38245, 18-00722

puncEndRE = re.compile(r"(\.|\!|\:)(\d{1,3})?$")

DelSupremeParaStart = re.compile(r"^\s*\(\d{1,3}\)\s[A-Z]")





prohibitedList_DEGOV = ["144670", "135640", "80280", "160340", "213920", "71240", 
                        "71240", "206330", "/Superior/pdf/admin_order_2015_1.pdf", 
                        "203680"]


startList0 = ['dear counsel']


DNPlist = ['Inc.', 'Inc.,', 'INC.', 'INC.,', 'Ltd.,', 'LTD.,', 'Ltd.', 'L.P.,', 'LLC,', 'LP,', 'LP',
           'Jr.', 'Jr.,', 'JR.,', 'Jr,', 'Sr.,', 'SR.,', 'III', 'III,', 'III.', 'III.;', 'IV,', 'California,',
           'LLC', 'L.L.C.', 'L.L.C.,', 'L.L.C.;', 'LLC.,', 'L.L.P.;', 'Jr.;', 'JR.;', 'Sr.;', 
           'Inc.;', 'INC.;', 'NA.,', 'N.A.,', 'M.D.', "Limited,", "Limited"]


partyWordsToRemove = ['\n', #SUPREME COURT STARTS HERE
 'third-party defendants', 'third-party plaintiffs', 'third-party defendant', 'third-party plaintiff',
 'nominal defendant below, appellee', 'nominal defendant below, appellant',
 'defendant below- appellant', 'plaintiff below- appellee',
 'respondent below- appellant', 'petitioner below- appellee', 'respondents below- appellees',
 'petitioner below, appellant', 'respondent below, appellee', 'petitioner below, appellee',
 'respondent below, appellant', 'petitioners below, appellants', 'respondents below, appellees',
 'petitioners below, appellees', 'respondents below, appellants', 'defendants below, appellants',
 'defendants below, appellees', 'plaintiffs below, appellants', 'plaintiffs below, appellees',
 'defendant below, appellant', 'defendant below, appellee', 'plaintiff below, appellant',
 'plaintiff below, appellee', 'defendants below-appellants', 'defendants below-appellees',
 'plaintiffs below-appellants', 'plaintiffs below-appellees', 'defendant below-appellant',
 'defendant below-appellee', 'plaintiff below-appellant', 'plaintiff below-appellee',
 'defendant/appellant below-appellant', 'plaintiffs/appellees below-appellees',
 'appellants', 'appellant', 'appellees', 'appellee',
 'below-appellant', 'below-appellee', 'plaintiff-employer below', 'plaintiff-employee below',
 'nominal plaintiffs', 'nominal defendants', 'nominal plaintiff', 'nominal defendant', #CHANCERY STARTS HERE
 'counter-plaintiffs', 'counter-plaintiff', 'counter-defendants', 'counter-defendant',
 'plaintiffs', 'plaintiff', 'defendants', 'defendant',
 'petitioners', 'petitioner', 'respondents', 'respondent', 'petitioning stockholders',
 'applicants', 'applicant', 'objectants below', 'objectant below',
 'a delaware corporation', 'a corporation of the state of delaware',
 'a delaware non-profit corporation', 'duly existing under the laws of the state of delaware',
 'a Delaware Limited Liability Company',
 'an oregon corporation', 'a connecticut corporation', 'a pennsylvania corporation',
 'a new jersey corporation',
 'a new york limited partnership', 'a new york corporation',
 'a corporation of the commonwealth of pennsylvania',
 'derivatively on behalf of', 'derivatively and on behalf of',
 'individually and on behalf of', 'all similarly situated individuals',
 '<br>',
 'a banking corporation of the State of Delaware',
 '/counterclaim', 'counterclaim', 'et al.', 't/a', 'f/k/a/', 'as receivers',
 'intervenors', 'intervenor-plaintiff', 'intervenor', 'a public corporation of the state of delaware',
 'and/or', 'as the board of directors of', 'a massachusetts corporation',
 'being the members of', 'trading as', 'his wife', '(two cases)',
 'a corporation',
 ', corporations ,',
 'a foreign corporation',
 'on behalf of themselves', 'on behalf of himself', 'on behalf of herself', 'on behalf of itself',
 'all others similarly situated', 'all other employees similarly situated',
 'individually and as trustees of the', 'individually and as trustee', 'invervening', 'deceased', 'dec\'d',
 'as officers and members of',
 'an alleged dependent child',
 'appeal of:',
 'executrix',
 'court below—family court of the state of delaware']


inReFirstCut = ['a minor child', 'respondent', 'et al., debtors', 'dated']


inReSecondCut = ['application of', 'in the matter of:', 'in the matter of',
                 'stockholder derivative litigation ii', 'stockholder derivative litigation',
                 'derivative litigation', 'for a general increase in rates', 'securities litigation',
                  'in re:', 'in re', 'stockholder litigation', 'stockholders litigation',
                  'the liquidation of', 'shareholder litigation', 'the appraisal of',
                  'appraisal of',
                  'a member of the bar of the supreme court of the state of delaware',
                  'shareholders litigation', 'litigation']


validEndPeriodWords = ['l.l.c.', 'inc.', 'corp.', 'co.', 'ltd.', 'l.p.',
                       'jr.', 'sr.']


interestFirstCut = ['appellant']


interestSecondCut = ['in the interest of:', 'in the interest of', 'in interest of', 'appeal of:', 
                     'in int. of', 'appeal of', 'appellant', 'a minor child', 'a minor', 'in re',
                     'natural father', 'father',
                     'natural mother', 'mother']


captionDQlist = ['decided:', 'date submitted:', 'draft report:', 'final report:', 
                 'telephone:', 'facsimile:']


sepLinesList = ['_____________________________\n', '____________________________________________\n']


IMOfirstCut = ['as trustee, ', 'dated ']


IMOsecondCut = ['IMO: ']



endReCaptionList = ['memorandum opinion', 'c.a. no', 'c. a. no', 'motion for', 'id no.', 'date submitted:',
                    'civil action no.', 'consolidated c.a. no.', 'consol. civil', 'consolidated civil',
                    'def. id', 'id no:', 'id. no', 'i.d. #', 'i.d. no', 'id nos', 'case no', 'case#',
                    'cr. a. no.', 'dear parties']


captionDQlist = ['decided:', 'date submitted:', 'draft report:', 'final report:', 
                 'telephone:', 'facsimile:']


captionTextList = ["on behalf of", "similarly situated", "derivatively on behalf",
                   "nominal defendant"]


PAsuperDelList = ['IN THE SUPERIOR COURT OF']


firstEntryTokens = ['1.', 'I.', 'i.', 'A.', 'a.', 
                    '(1)', '(I)', '(i)', '(A)', '(a)',
                    '1)', 'I)', 'i)', 'A)', 'a)']


secondEntryTokens = ['2.', 'II.', 'ii.', 'B.', 'b.', 
                    '(2)', '(II)', '(ii)', '(B)', '(b)',
                    '2)', 'II)', 'ii)', 'B)', 'b)']


firstToSecond = {'1.':'2.', 'I.':'II.', 'i.':'ii.', 'A.':'B.', 'a.':'b.', 
                    '(1)':'(2)', '(I)':'(II)', '(i)':'(ii)', '(A)':'(B)', '(a)':'(b)',
                    '1)':'2)', 'I)':'II)', 'i)':'ii):', 'A)':'B)', 'a)':'b)'}


headerDict = {'1.':['1.', '2.', '3.', '4.', '5.', '6.', '7.', '8.', '9.', '10.', '11.', '12.', '13.', '14.', '15.', '16.', '17.', '18.', '19.', '20.', '21.', '22.', '23.', '24.', '25.', '26.', '27.', '28.', '29.', '30.'], 
              'I.':['I.', 'II.', 'III.', 'IV.', 'V.', 'VI.', 'VII.', 'VIII.', 'IX.', 'X.', 'XI.', 'XII.', 'XIII.', 'XIV.', 'XV.', 'XVI.', 'XVII.', 'XVIII.', 'XIX.', 'XX.', 'XXI.', 'XXII.', 'XXIII.', 'XXIV.', 'XXV.', 'XXVI.', 'XXVII.', 'XXVIII.', 'XXIX.', 'XXX.'], 
              'i.':['i.', 'ii.', 'iii.', 'iv.', 'v.', 'vi.', 'vii.', 'viii.', 'ix.', 'x.', 'xi.', 'xii.', 'xiii.', 'xiv.', 'xv.', 'xvi.', 'xvii.', 'xviii.', 'xix.', 'xx.', 'xxi.', 'xxii.', 'xxiii.', 'xxiv.', 'xxv.', 'xxvi.', 'xxvii.', 'xxviii.', 'xxix.', 'xxx.'],
              'A.':['A.', 'B.', 'C.', 'D.', 'E.', 'F.', 'G.', 'H.', 'I.', 'J.', 'K.', 'L.', 'M.', 'N.', 'O.', 'P.', 'Q.', 'R.', 'S.', 'T.', 'U.', 'V.', 'W.', 'X.', 'Y.', 'Z.', 'AA.', 'BB.', 'CC.', 'DD.', 'EE.'],
              'a.':['a.', 'b.', 'c.', 'd.', 'e.', 'f.', 'g.', 'h.', 'i.', 'j.', 'k.', 'l.', 'm.', 'n.', 'o.', 'p.', 'q.', 'r.', 's.', 't.', 'u.', 'v.', 'w.', 'x.', 'y.', 'z.', 'aa.', 'bb.', 'cc.', 'dd.', 'ee.'],
              '(1)':['(1)', '(2)', '(3)', '(4)', '(5)', '(6)', '(7)', '(8)', '(9)', '(10)', '(11)', '(12)', '(13)', '(14)', '(15)', '(16)', '(17)', '(18)', '(19)', '(20)', '(21)', '(22)', '(23)', '(24)', '(25)', '(26)', '(27)', '(28)', '(29)', '(30)'],
              '(I)':['(I)', '(II)', '(III)', '(IV)', '(V)', '(VI)', '(VII)', '(VIII)', '(IX)', '(X)', '(XI)', '(XII)', '(XIII)', '(XIV)', '(XV)', '(XVI)', '(XVII)', '(XVIII)', '(XIX)', '(XX)', '(XXI)', '(XXII)', '(XXIII)', '(XXIV)', '(XXV)', '(XXVI)', '(XXVII)', '(XXVIII)', '(XXIX)', '(XXX)'],
              '(i)':['(i)', '(ii)', '(iii)', '(iv)', '(v)', '(vi)', '(vii)', '(viii)', '(ix)', '(x)', '(xi)', '(xii)', '(xiii)', '(xiv)', '(xv)', '(xvi)', '(xvii)', '(xviii)', '(xix)', '(xx)', '(xxi)', '(xxii)', '(xxiii)', '(xxiv)', '(xxv)', '(xxvi)', '(xxvii)', '(xxviii)', '(xxix)', '(xxx)'], 
              '(A)':['(A)', '(B)', '(C)', '(D)', '(E)', '(F)', '(G)', '(H)', '(I)', '(J)', '(K)', '(L)', '(M)', '(N)', '(O)', '(P)', '(Q)', '(R)', '(S)', '(T)', '(U)', '(V)', '(W)', '(X)', '(Y)', '(Z)', '(AA)', '(BB)', '(CC)' ,'(DD)', '(EE)'],
              '(a)':['(a)', '(b)', '(c)', '(d)', '(e)', '(f)', '(g)', '(h)', '(i)', '(j)', '(k)', '(l)', '(m)', '(n)', '(o)', '(p)', '(q)', '(r)', '(s)', '(t)', '(u)', '(v)', '(w)', '(x)', '(y)', '(z)', '(aa)', '(bb)', '(cc)', '(dd)', '(ee)'],
              '1)':['1)', '2)', '3)', '4)', '5)', '6)', '7)', '8)', '9)', '10)', '11)', '12)', '13)', '14)', '15)', '16)', '17)', '18)', '19)', '20)', '21)', '22)', '23)', '24)', '25)', '26)', '27)', '28)', '29)', '30)'],
              'I)':['I)', 'II)', 'III)', 'IV)', 'V)', 'VI)', 'VII)', 'VIII)', 'IX)', 'X)', 'XI)', 'XII)', 'XIII)', 'XIV)', 'XV)', 'XVI)', 'XVII)', 'XVIII)', 'XIX)', 'XX)', 'XXI)', 'XXII)', 'XXIII)', 'XXIV)', 'XXV)', 'XXVI)', 'XXVII)', 'XXVIII)', 'XXIX)', 'XXX)'], 
              'i)':['i)', 'ii)', 'iii)', 'iv)', 'v)', 'vi)', 'vii)', 'viii)', 'ix)', 'x)', 'xi)', 'xii)', 'xiii)', 'xiv)', 'xv)', 'xvi)', 'xvii)', 'xviii)', 'xix)', 'xx)', 'xxi)', 'xxii)', 'xxiii)', 'xxiv)', 'xxv)', 'xxvi)', 'xxvii)', 'xxviii)', 'xxix)', 'xxx)'],
              'A)':['A)', 'B)', 'C)', 'D)', 'E)', 'F)', 'G)', 'H)', 'I)', 'J)', 'K)', 'L)', 'M)', 'N)', 'O)', 'P)', 'Q)', 'R)', 'S)', 'T)', 'U)', 'V)', 'W)', 'X)', 'Y)', 'Z)', 'AA)', 'BB)', 'CC)' ,'DD)', 'EE)'],
              'a)':['a)', 'b)', 'c)', 'd)', 'e)', 'f)', 'g)', 'h)', 'i)', 'j)', 'k)', 'l)', 'm)', 'n)', 'o)', 'p)', 'q)', 'r)', 's)', 't)', 'u)', 'v)', 'w)', 'x)', 'y)', 'z)', 'aa)', 'bb)', 'cc)', 'dd)', 'ee)']}


stackedCharStartLines = ["in the court of chancery", "in the supreme court",
                         "in the superior court", "in the court of common",
                         "in and for new castle", "in and for kent", 
                         "in and for sussex"]




# Key = Jurisdiction and Court as in database; value = Bluebook court abbreviation
courtAbbDict = {('Delaware', 'Supreme Court'):'Del.',
                ('Delaware', 'Court of Chancery'):'Del. Ch.',
                ('Delaware', 'Superior Court'):'Del. Super.',
                ('Delaware', 'Court of Common Pleas'):'Del. C.C.P.',
                ('Delaware', 'Court on the Judiciary'):'Del. Jud. Ct.',
                ('Delaware', 'Family Court'):'Del. Fam.',
                ('Pennsylvania', 'Supreme Court'):'Pa.',
                ('Pennsylvania', 'Commonwealth Court'):'Pa. Common.',
                ('Pennsylvania', 'Superior Court'):'Pa. Super.',
                ('Pennsylvania', 'Court of Judicial Discipline'):'Pa. Jud. Ct.',
                ('United States', 'Supreme Court'):'U.S.',
                ('United States', 'SCOTUS'):'U.S.',
                ('United States', 'Second Circuit'):'2d Cir.',
                ('United States', 'Third Circuit'):'3d Cir.',
                ('United States', 'District of Delaware'):'D. Del.',
                ('United States', 'District of New Jersey'):'D.N.J.',
                ('United States', 'Eastern District of Pennsylvania'):'E.D.P.A.',
                ('United States', 'Middle District of Pennsylvania'):'M.D.P.A.',
                ('United States', 'Western District of Pennsylvania'):'W.D.P.A.'}



# TABLE 6 OF BLUEBOOK (with minor additions, e.g., 'stockholder')
### NEED TO ADD PLURALS!!!
slugAbbDict = {
    "academic":"acad.",
    "academy":"acad.",
    "academies":"acads.",
    "administrative":"admin.",
    "administration":"admin.",
    "administrations":"admins.",
    "administrator":"adm'r",
    "administrators":"adm'rs",
    "administratrix":"adm'x",
    "advertising":"advert.",
    "agriculture":"agric.",
    "agricultural":"agric.",
    "alliance":"all.",
    "alliances":"alls.",
    "alternative":"alt.",
    "alternatives":"alts.",
    "america":"am.",
    "american":"am.",
    "and":"&",
    "associate":"assoc.",
    "associates":"assocs.",
    "association":"ass'n",
    "associations":"ass'ns",
    "atlantic":"atl.",
    "authority":"auth.",
    "authorities":"auths.",
    "automobile":"auto.", 
    "automobiles":"autos.",
    "automotive":"auto.",
    "avenue":"ave.",
    "avenues":"aves.",
    "bankruptcy":"bankr.",
    "bankruptcies":"bankrs.",
    "board":"bd.",
    "boars":"bds.",
    "broadcaster":"broad.",
    "boradcasters":"broads.",
    "broadcasting":"broad.",
    "brotherhood":"bhd.",
    "brotherhoods":"bhds.",
    "brothers":"bros.",
    "building":"bldg.",
    "buildings":"bldgs.",
    "business":"bus.",
    "businesses":"buss.",
    "casualty":"cas.",
    "center":"ctr.",
    "centers":"ctrs.",
    "centre":"ctr.",
    "centres":"ctrs.",
    "central":"cent.",
    "chemical":"chem.",
    "chemicals":"chems.",
    "coalition":"coal.",
    "coalistions":"coals.",
    "college":"coll.",
    "collegs":"colls.",
    "commission":"comm'n",
    "commissions":"comm'ns",
    "commissioner":"comm'r",
    "commissioners":"comm'rs",
    "committee":"comm.",
    "committees":"comms.",
    "communication":"commc'n",
    "communications":"commc'ns",
    "community":"cmty.",
    "communities":"cmtys.",
    "company":"co.",
    "companies":"cos.",
    "compensation":"comp.",
    "compensations":"comp.",
    "computer":"comput.",
    "coputers":"computs.",
    "condominium":"condo.",
    "condominiums":"condos.",
    "congress":"cong.",
    "congresses":"congs.",
    "congressional":"cong.",
    "consolidated":"consol.",
    "construction":"constr.",
    "constructions":"constr.",
    "continental":"cont'l",
    "continentals":"cont'ls",
    "cooperative":"coop.",
    "cooperatives":"coops.",
    "corporate":"corp.",
    "corporation":"corp.",
    "corporations":"corps.",
    "correction":"corr.",
    "corrections":"corr.",
    "correctional":"corr.",
    "county":"cty.",
    "counties":"ctys.",
    "defender":"def.",
    "defenders":"defs.",
    "defense":"def.",
    "department":"dep't",
    "departments":"dep'ts",
    "derivative":"deriv.",
    "detention":"det.",
    "development":"dev.",
    "developments":"devs.",
    "digital":"dig.",
    "director":"dir.",
    "directors":"dirs.",
    "discount":"disc.",
    "discounts":"discs.",
    "distributor":"distrib.",
    "distributors":"distribs.",
    "distributing":"distrib.",
    "distribution":"distrib.",
    "district":"dist.",
    "districts":"dists.",
    "division":"div.",
    "divisions":"divs.",
    "east":"e.",
    "eastern":"e.",
    "economic":"econ.",
    "economical":"econ.",
    "economics":"econ.",
    "economy":"econ.",
    "economies":"econs.",
    "education":"educ.",
    "educational":"educ.",
    "electric":"elec.",
    "electrical":"elec.",
    "electricity":"elec.",
    "electronic":"elec.",
    "electronics":"elecs.",
    "employee":"emp.",
    "employees":"emps.",
    "employer":"emp'r",
    "employers":"emp'rs",
    "employment":"emp't",
    "employments":"emp'ts",
    "enforcement":"enf't",
    "enforcements":"enf'ts",
    "engineer":"eng'r",
    "engineers":"eng'rs",
    "engineering":"eng'g",
    "enterprise":"enter.",
    "enterprises":"enters.",
    "entertainment":"entm't",
    "entertainments":"entm'ts",
    "environment":"env't",
    "environments":"env'ts",
    "environmental":"envtl.",
    "equality":"equal.",
    "equalities":"equals.",
    "equipment":"equip.",
    "equipments":"equips.",
    "examiner":"exam'r",
    "examiners":"exam'rs",
    "exchange":"exch.",
    "exchanges":"exch.",
    "executive":"exec.",
    "executives":"execs.",
    "executor":"ex'r",
    "executors":"ex'rs",
    "executrix":"ex'x",
    "exploration":"expl.",
    "explorations":"expls.",
    "exploratory":"expl.",
    "export":"exp.",
    "exports":"exps.",
    "exporter":"exp.",
    "exporters":"exps.",
    "exportation":"exp.",
    "federal":"fed.",
    "federation":"fed'n",
    "federations":"fed'ns",
    "fidelity":"fid.",
    "fidelities":"fids.",
    "finance":"fin.",
    "finances":"fins.",
    "financial":"fin.",
    "financing":"fin.",
    "foundation":"found.",
    "foundations":"founds.",
    "general":"gen.",
    "generals":"gens.",
    "global":"glob.",
    "government":"gov't",
    "governments":"gov'ts",
    "group":"grp.",
    "groups":"grps.",
    "guaranty":"guar.",
    "guaranties":"guars.",
    "hospital":"hosp.",
    "hospitals":"hosps.",
    "hospitality":"hosp.",
    "housing":"hous.",
    "import":"imp.",
    "imports":"imps.",
    "importer":"imp.",
    "imports":"imps.",
    "importation":"imp.",
    "incorporated":"inc.",
    "indemnity":"indem.",
    "indemnities":"indems.",
    "independence ":"indep.",
    "independent":"indep.",
    "industry":"indus.",
    "industries":"indus.",
    "industrial":"indus.",
    "information":"info.",
    "institute":"inst.",
    "institutes":"insts.",
    "instituion":"inst.",
    "institutions":"insts.",
    "insurance":"ins.",
    "international":"int'l",
    "investment":"inv.",
    "investments":"invs.",
    "investor":"inv'r",
    "investors":"inv'rs",
    "laboratory":"lab.",
    "laboratories":"labs.",
    "liability":"liab.",
    "liabilities":"liabs.",
    "limited":"ltd.",
    "litigation":"litig.",
    "litigations":"litigs.",
    "machine":"mach.",
    "machines":"machs.",
    "machinery":"mach.",
    "maintenance":"maint.",
    "management":"mgmt.",
    "managements":"mgmts.",
    "manufacturer":"mfr.",
    "manufacturers":"mfrs.",
    "manufacturing":"mfg.",
    "maritime":"mar.",
    "market":"mkt.",
    "markets":"mkts.",
    "marketing":"mktg.",
    "mechanic":"mech.",
    "mechanical":"mech.",
    "medical":"med.",
    "medicine":"med.",
    "memorial":"mem'l",
    "memorials":"mem'ls",
    "merchant":"merch.",
    "merchants":"merchs.",
    "merchandise":"med.",
    "merchanidising":"merch.",
    "metropolitan":"metro.",
    "metropolitans":"metros.",
    "mortgage":"mortg.",
    "mortgages":"mortgs.",
    "municipal":"mun.",
    "mutual":"mut.",
    "national":"nat'l",
    "natural":"nat.",
    "north":"n.",
    "northern":"n.",
    "northeast":"ne.",
    "northeastern":"ne.",
    "northwest":"nw.",
    "northwestern":"nw.",
    "number":"no.",
    "numbers":"nos.",
    "opinion":"op.",
    "opinions":"ops.",
    "organization":"org.",
    "organizations":"orgs.",
    "organizing":"org.",
    "pacific":"pac.",
    "parish":"par.",
    "parishes":"pars.",
    "partnership":"p'ship",
    "partnerships":"p'ships",
    "person":"pers.",
    "persons":"pers.",
    "personal":"pers.",
    "personnel":"pers.",
    "pharmaceutics":"pharm.",
    "pharmaceutical":"pharm.",
    "pharmaceuticals":"pharm.",
    "preserve":"pres.",
    "preservation":"pres.",
    "probate":"prob.",
    "probates":"probs.",
    "probation":"prob.",
    "probations":"probs.",
    "product":"prod.",
    "products":"prods.",
    "production":"prod.",
    "productions":"prods.",
    "professional":"prof'l",
    "professionals":"prof'ls",
    "property":"prop.",
    "properties":"props.",
    "protection":"prot.",
    "public":"pub.",
    "publication":"publ'n",
    "publications":"publ'ns",
    "publishing":"publ'g",
    "railroad":"R.R.",
    "railroads":"R.R.s",
    "railway":"ry.",
    "railways":"rys.",
    "refining":"ref.",
    "regional":"reg'l",
    "rehabilitation":"rehab.",
    "rehabilative":"rehab.",
    "reproduction":"rehab.",
    "reproductive":"reprod.",
    "resource":"res.",
    "resources":"res.",
    "restaurant":"rest.",
    "restaurants":"rests.",
    "retirement":"ret.",
    "retirements":"rets.",
    "road":"rd.",
    "roads":"rds.",
    "savings":"sav.",
    "school":"sch.",
    "schools":"sch.",
    "science":"sci.",
    "sciences":"scis.",
    "scientific":"sci.",
    "secretary":"sec'y",
    "secretaries":"sec'ys",
    "security":"sec.",
    "securities":"sec.",
    "service":"serv.",
    "services":"servs.",
    "shareholder":"s'holder",
    "shareholders":"s'holders",
    "stockholder":"s'holder",
    "stockholders":"s'holders",
    "social":"soc.",
    "society":"soc'y",
    "societies":"soc'ys",
    "solution":"sol.",
    "solutions":"sols.",
    "south":"s.",
    "southern":"s.",
    "southeast":"se.",
    "southeastern":"se.",
    "southwest":"sw.",
    "southwestern":"sw.",
    "steamship":"S.S.",
    "steamships":"S.S.",
    "street":"st.",
    "streets":"sts.",
    "subcommittee":"subcomm.",
    "subcommittees":"subcomms.",
    "surety":"sur.",
    "sureties":"surs.",
    "system":"sys.",
    "systems":"sys.",
    "technical":"tech.",
    "technological":"tech.",
    "technology":"tech.",
    "technologies":"techs.",
    "telecommunication":"telecomm.",
    "telephone":"tel.",
    "telephones":"tels.",
    "telegraph":"tel.",
    "telegraphs":"tels.",
    "temporary":"temp.",
    "township":"twp.",
    "townships":"twps.",
    "transcontinental":"transcon.",
    "transport":"transp.",
    "transports":"transps.",
    "transportation":"transp.",
    "trust":"tr.",
    "trusts":"trs.",
    "trustee":"tr.",
    "trustees":"trs.",
    "turnpike":"tpk.",
    "turnpkes":"tpks.",
    "uniform":"unif.",
    "uniforms":"unifs.",
    "university":"univ.",
    "universities":"univs.",
    "utility":"util.",
    "utilities":"utils.",
    "village":"vill.",
    "villages":"vills.",
    "west":"w.",
    "western":"w."}
